title: KerchooKult
description: software development & other projects
show_downloads: false
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/KerchooKult/kerchookult.github.io
discord_url: https://discord.gg/6a56vK9
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
